Repository serverless/serverless-python-requirements, pull requests merged in 2022-10, with the labels that each got.

#732 ci: Run CI tests against Serverless v3
  .github/workflows/integrate.yml
  .github/workflows/validate.yml
Labels: tests

#728 feat: Introduce `requirePoetryLockFile` flag
  README.md
  index.js
  lib/poetry.js
  test.js
  tests/poetry/serverless.yml
Labels: enhancement

#718 fix: Adapt to support latest `pipenv` version
  .github/workflows/integrate.yml
  .github/workflows/validate.yml
  lib/pipenv.js
  tests/pipenv/Pipfile
Labels: enhancement

#724 feat: Switch to official AWS docker images by default
  index.js
Labels: enhancement, breaking-change
